---
title: "ZOMATO"
output: html_notebook
---

```{r}
zomato <- read.csv("zomato.csv")
```
```{r}
summary(zomato)
```

```{r}
head(zomato)
```
```{r}
print(zomato)
```
```{r}
sum(is.na(zomato))
```
```{r}
summary(zomato$rate)

```
```{r}
summary(zomato$numofratings)

```
```{r}
summary(zomato$avgCost)

```

```{r}
boxplot.stats(zomato$rate)$out

```

```{r}
boxplot.stats(zomato$avgCost)$out

```

```{r}
boxplot.stats(zomato$numofratings)$out

```

```{r}
boxplot(zomato$rate)

```

```{r}
boxplot(zomato$numofratings)

```

```{r}
boxplot(zomato$avgCost)

```

```{r}
plot(zomato$rate,zomato$avgCost)

```

```{r}
hist(zomato$avgCost)
```

```{r}
onlineOrder <- table(zomato$online_order)
pie(onlineOrder)
```

```{r}
summary (zomato$rate)

```

```{r}
summary(zomato$numofratings)

```

```{r}
summary(zomato$avgCost)

```

```{r}
dim(zomato)

```

```{r}
zomato =na.omit(zomato)

```

```{r}
dim(zomato)

```

```{r}
sum(is.na(zomato))

```

```{r}
library(outliers)
```

```{r}
OutN = outlier(zomato$numofratings, logical =TRUE)

```

```{r}
sum(OutN)

```

```{r}
Find_outlier = which(OutN ==TRUE, arr.ind = TRUE)

```

```{r}
OutN
```

```{r}
Find_outlier

```

```{r}
zomato= zomato[-Find_outlier,]

```

```{r}
OutAv = outlier(zomato$avgCost, logical =TRUE)
sum(OutAv)

```

```{r}
Find_outlier = which(OutAv ==TRUE, arr.ind = TRUE)
OutAv

```

```{r}
Find_outlier
```

```{r}
zomato= zomato[-Find_outlier,]
```

```{r}
set.seed(7)

```

```{r}
library(mlbench)
library(caret)
library(caret)
library(randomForest)

```

```{r}
zomato$rate <- as.factor(zomato$rate )

```

```{r}
predictors <- zomato[, -5]  # Excluding the class label (satisfaction)
class_label <- zomato$rate 

```

```{r}
model <- randomForest(predictors, class_label, importance = TRUE)

```

```{r}
importance <- importance(model)

ranked_features <- sort(importance[, "MeanDecreaseGini"], decreasing = TRUE)

```

```{r}
barplot(ranked_features, horiz = TRUE, col = c("lightblue2"), las = 1, main = "Airline satisfaction Variable Import")

```

```{r}
control <- rfeControl(functions=rfFuncs, method="cv", number=10)

```

```{r}
results <- rfe(zomato[,11:11], zomato[,12], sizes=c(1:11), rfeControl=control)

```

```{r}
print(results)

```

```{r}
predictors(results)

```

```{r}
plot(results, type=c("g", "o"))
```

```{r}
library(ROSE)
```

```{r}
zomato$rate <- as.factor(zomato$rate)
zomato<-upSample(zomato[,-5],zomato$rate, yname="rate")
plot(zomato$rate)

```

```{r}
prop.table(table(zomato$rate))
```

```{r}
title(main="Data after oversampling", xlab="rate", ylab="observations")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

